FROM docker.io/nginx:1-alpine-slim

WORKDIR /build

RUN apk --no-cache add zola

COPY . .

ARG BASE_URL
ENV BASE_URL="${BASE_URL}"

EXPOSE 1024

COPY nginx/default.dev.conf /etc/nginx/conf.d/default.conf
COPY nginx/entrypoint.dev.sh /docker-entrypoint.d/99-custom.sh
