#!/usr/bin/env bash

find . \
    -type f \
    -not -path "./.git/*" \
    -not -path "./.reuse/*" \
    -not -path "./public/*" \
    -not -path "./static/icons/*" \
    -exec reuse annotate \
    --copyright "Pavel Sobolev" \
    --copyright-prefix string \
    --year 2025 \
    --license "Apache-2.0" \
    --template apache \
    --skip-unrecognised \
    --merge-copyrights \
    {} +
